### PR TITLE
Update REAMDE.md to match changes to the website

### PR DESCRIPTION
**Pull request by EmilePW**

### CODE REVIEW

**Review by apcros — APPROVED** [review]
Duplicate of the other PR, close the other one if you merge this

**Comment by EmilePW** [comment]
Hi @apcros , it's not a duplicate - that one is for the text on the homepage, this is for the repo's README

**Comment by apcros** [comment]
> Hi @apcros , it's not a duplicate - that one is for the text on the homepage, this is for the repo's README

Haha sorry I obviously can't read, thanks

**Comment by EmilePW** [comment]
@apcros I don't have push access btw, not sure if you do?

**Comment by apcros** [comment]
> @apcros I don't have push access btw, not sure if you do?

Want me to hit merge ? I can

**Comment by EmilePW** [comment]
> > @apcros I don't have push access btw, not sure if you do?
> 
> Want me to hit merge ? I can

Yes please

**Pull request merged**
